# Generated by Django 5.0.6 on 2024-05-30 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_group',
            old_name='status',
            new_name='class_group_status',
        ),
        migrations.RenameField(
            model_name='class_group',
            old_name='user',
            new_name='class_user',
        ),
        migrations.RenameField(
            model_name='tutor_child',
            old_name='user',
            new_name='tutor_user',
        ),
    ]
