# Generated by Django 5.0.6 on 2024-05-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros', '0002_rename_status_class_group_class_group_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(default=0, max_length=160),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='password',
            field=models.CharField(default=0, max_length=160),
        ),
    ]
